# Generated by Django 2.1.5 on 2019-02-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='iamges/')),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
    ]
